
/****** Object:  Database [BDESTACIONAMENTO]    Script Date: 24/10/2022 15:31:24 ******/
CREATE DATABASE [BDESTACIONAMENTO]
GO
USE [BDESTACIONAMENTO]
GO
/****** Object:  Table [dbo].[CLIENTE]    Script Date: 24/10/2022 15:31:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTE](
	[CodCliente] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](60) NOT NULL,
	[Celular] [varchar](13) NOT NULL,
	[Email] [varchar](80) NOT NULL,
 CONSTRAINT [PKCodCliente] PRIMARY KEY CLUSTERED 
(
	[CodCliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ESTACIONA]    Script Date: 24/10/2022 15:31:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ESTACIONA](
	[CodEstaciona] [int] IDENTITY(1,1) NOT NULL,
	[Placa] [char](7) NULL,
	[DataHoraEntrada] [datetime] NULL,
	[DataHoraSaida] [datetime] NULL,
	[Valor] [money] NULL,
 CONSTRAINT [PKCodEstaciona] PRIMARY KEY CLUSTERED 
(
	[CodEstaciona] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MARCA]    Script Date: 24/10/2022 15:31:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MARCA](
	[CodMarca] [int] IDENTITY(1,1) NOT NULL,
	[NomeMarca] [varchar](50) NOT NULL,
 CONSTRAINT [PKCodMarca] PRIMARY KEY CLUSTERED 
(
	[CodMarca] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VEICULO]    Script Date: 24/10/2022 15:31:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VEICULO](
	[Placa] [char](7) NOT NULL,
	[Modelo] [varchar](50) NOT NULL,
	[CodMarca] [int] NULL,
	[Cor] [varchar](20) NOT NULL,
	[Ano] [date] NULL,
	[CodCliente] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PKPlaca] PRIMARY KEY CLUSTERED 
(
	[Placa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESTACIONA]  WITH CHECK ADD  CONSTRAINT [FKPlaca] FOREIGN KEY([Placa])
REFERENCES [dbo].[VEICULO] ([Placa])
GO
ALTER TABLE [dbo].[ESTACIONA] CHECK CONSTRAINT [FKPlaca]
GO
ALTER TABLE [dbo].[VEICULO]  WITH CHECK ADD  CONSTRAINT [FKCodCliente] FOREIGN KEY([CodCliente])
REFERENCES [dbo].[CLIENTE] ([CodCliente])
GO
ALTER TABLE [dbo].[VEICULO] CHECK CONSTRAINT [FKCodCliente]
GO
ALTER TABLE [dbo].[VEICULO]  WITH CHECK ADD  CONSTRAINT [FKCodMarca] FOREIGN KEY([CodMarca])
REFERENCES [dbo].[MARCA] ([CodMarca])
GO
ALTER TABLE [dbo].[VEICULO] CHECK CONSTRAINT [FKCodMarca]
GO
USE [master]
GO
ALTER DATABASE [BDESTACIONAMENTO] SET  READ_WRITE 
GO
